src/AppBundle/Entity/Download.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Karwana\Mime\Mime;

/**
 * Class Download
 * @package AppBundle\Entity
 * @ORM\Entity
 * @ORM\Table(name="downloads")
 * @ORM\HasLifecycleCallbacks
 */
class Download
{
    /**
     * @var integer
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=1024)
     */
    private $url = '';

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $filename = '';

    /**
     * @var string
     * @ORM\Column(type="string", length=1024)
     */
    private $referer = '';

    /**
     * @var string
     * @ORM\Column(type="text", length=65535)
     */
    private $comment = '';

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $downloaded = false;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $created = null;

    /**
     * @var string
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $checksum = null;

    /**
     * @var Metadatum[]
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Metadatum", mappedBy="download", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $metadata;

    /**
     * @var bool
     * @ORM\Column(type="boolean", options={"default" = 0})
     */
    private $failed = false;

    /**
     * Download constructor.
     */
    public function __construct()
    {
        $this->metadata = new ArrayCollection();
        $this->created = new \DateTime();
    }

    /**
     * @return string
     */
    public function getChecksum()
    {
        if (!isset($this->checksum)) {
            $this->calculateChecksum();
        }
        return $this->checksum;
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * @param string $filename
     * @return Download
     */
    public function setFilename($filename)
    {
        $filename = str_replace(
            ['<', '>', ':',   '"', '/',   '\\',  '|',   '?', '*'],
            ['(', ')', ' - ', "'", ' - ', ' - ', ' - ', '',  '+'],
            $filename
        );
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return boolean
     */
    public function isDownloaded()
    {
        return $this->downloaded;
    }

    /**
     * @param boolean $downloaded
     * @return Download
     */
    public function setDownloaded($downloaded)
    {
        $this->downloaded = $downloaded;
        $this->checksum = null;
        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $title
     * @param string $value
     * @return Metadatum
     */
    public function addMetadatum($title, $value)
    {
        $metadatum = new Metadatum();
        $metadatum->setTitle($title)->setValue($value)->setDownload($this);
        $this->metadata->add($metadatum);
        return $metadatum;
    }

    /**
     * Get metadata
     * @return Collection
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @ORM\PrePersist
     */
    public function calculateChecksum()
    {
        $this->checksum = md5($this->getUrl() . $this->getReferer());
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param string $url
     * @return Download
     */
    public function setUrl($url)
    {
        $this->url = $url;
        $this->checksum = null;
        return $this;
    }

    /**
     * @return string
     */
    public function getReferer()
    {
        return $this->referer;
    }

    /**
     * @param string $referer
     * @return Download
     */
    public function setReferer($referer)
    {
        $this->referer = $referer;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $result = [];
        foreach ($this->metadata as $metadatum) {
            $result[] = $metadatum->getTitle() . ': ' . $metadatum->getValue();
        }
        $result[] = '======================================';
        $result[] = $this->getComment();
        return implode(PHP_EOL, $result);
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     * @return Download
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
        return $this;
    }

    /**
     * @return int|string
     */
    public function getMimetype()
    {
        return Mime::getTypeForExtension($this->getExtension());
    }

    /**
     * @return string
     */
    public function getExtension()
    {
        return pathinfo($this->getFilename(), PATHINFO_EXTENSION);
    }

    /**
     * @return boolean
     */
    public function isFailed()
    {
        return $this->failed;
    }

    /**
     * @param boolean $failed
     * @return Download
     */
    public function setFailed($failed)
    {
        $this->failed = $failed;
        return $this;
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Command\DownloadCommand;
use AppBundle\Entity\Download;
use AppBundle\Entity\Metadatum;
use AppBundle\Entity\Notification;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Console\Output\NullOutput;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    const PAGE_SIZE = 15;

    public function allAction($page)
    {
        return $this->indexAction($page, true);
    }

    public function indexAction($page, $showDownloaded = false)
    {
        $em = $this->container->get('doctrine.orm.entity_manager');
        $repo = $em->getRepository('AppBundle:Download');
        $total = $repo
            ->createQueryBuilder('d')
            ->select('count(d.id)');
        if (!$showDownloaded) {
            $total->andWhere('d.downloaded = false');
        }
        $total = $total
            ->getQuery()
            ->getSingleScalarResult();
        $pageCount = ceil(abs($total - 1) / self::PAGE_SIZE);

        if ($page > $pageCount) {
            return $this->redirectToRoute($showDownloaded ? 'app_list_all_downloads' : 'app_list_downloads', ['page' => $pageCount]);
        } elseif ($page < 1) {
            return $this->redirectToRoute($showDownloaded ? 'app_list_all_downloads' : 'app_list_downloads', ['page' => 1]);
        }

        $offset = ($page - 1) * self::PAGE_SIZE;
        $queryBuilder = $repo->createQueryBuilder('d')
                             ->select('d.id')
                             ->orderBy('d.created')
                             ->setMaxResults(self::PAGE_SIZE)
                             ->setFirstResult($offset);
        if (!$showDownloaded) {
            $queryBuilder->andWhere('d.downloaded = false');
        }
        $downloadIds = $queryBuilder
            ->getQuery()
            ->getResult();
        $downloads = [];
        foreach ($downloadIds as $downloadId) {
            $downloads[] = $repo->find($downloadId['id']);
        }
        return $this->render(
            'AppBundle:Default:index.html.twig',
            [
                'page'           => $page,
                'firstPage'      => $page == 1,
                'lastPage'       => $page == $pageCount,
                'downloads'      => $downloads,
                'total'          => $total,
                'pageCount'      => $pageCount,
                'showDownloaded' => $showDownloaded,
                'stats'          => $this->container->get('app.stats')->getStats(),
            ]
        );
    }

    public function downloadAction(Request $request, $id)
    {
        $downloadCmd = new DownloadCommand();
        $downloadCmd->setContainer($this->container);
        $downloadCmd->download(new NullOutput(), $id);
        $this->get('doctrine.orm.entity_manager')->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    public function deleteAction(Request $request, $id)
    {
        $em = $this->get('doctrine.orm.entity_manager');
        $repo = $em->getRepository('AppBundle:Download');
        $download = $repo->find($id);
        $em->remove($download);
        $em->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    public function notificationAction($id)
    {
        $notification = $this
            ->container
            ->get('doctrine.orm.entity_manager')
            ->getRepository('AppBundle:Notification')
            ->find($id);
        return $this->render(
            'AppBundle:Default:notification.html.twig',
            [
                'notification' => $notification,
                'stats'        => $this->container->get('app.stats')->getStats(),
            ]
        );
    }

    public function putDownloadAction(Request $request)
    {
        $items = json_decode($request->getContent(), JSON_OBJECT_AS_ARRAY);
        if (isset($items['url'])) {
            $items = [$items];
        }

        $em = $this->container->get('doctrine.orm.default_entity_manager');
        $skipped = 0;
        $saved = 0;
        foreach ($items as $item) {
            $downloadEntity = new Download();
            $downloadEntity
                ->setUrl($item['url'])
                ->setComment($item['comment'])
                ->setFilename($item['filename'])
                ->setReferer($item['referer']);
            foreach ($item['metadata'] as $key => $value) {
                $downloadEntity->addMetadatum($key, $value);
            }
            $existQuery = $em->getRepository('AppBundle:Download')
                             ->createQueryBuilder('d')
                             ->select('d.id')
                             ->where('d.checksum = :checksum')
                             ->getQuery();
            $existQuery->execute(['checksum' => $downloadEntity->getChecksum()]);
            if (count($existQuery->getArrayResult()) === 0) {
                $em->persist($downloadEntity);
                $saved++;
            } else {
                $skipped++;
            }
            if (($saved + $skipped) % 500 === 0) {
                $em->flush();
            }
        }
        $notification = new Notification($saved > 100);
        $notification
            ->setType('info')
            ->setTitle('Scan successful')
            ->setText("{$saved} saved, {$skipped} skipped, 0 enqueued");
        $em->persist($notification);
        $em->flush();
        return new JsonResponse($notification);
    }
}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block header %}
    <header>
        <div class="stats">
            <span>Downloads: {{ stats['Not Downloaded'] }} / {{ stats['Total'] }}</span>
            <span>Enqueued: {{ stats['Enqueued'] }}</span>
        </div>
    </header>
{% endblock %}

{% block body %}
    <main>
        <table>
            {# @var download \AppBundle\Entity\Download #}
            {% for download in downloads %}
                <tr class="{{ cycle(['odd', 'even'], loop.index) }}{% if download.downloaded %} downloaded{% endif %}{% if download.failed %} failed{% endif %}">
                    <td class="icon"><span class="fa {{ download.mimetype|faFileIcon }}"></span></td>
                    <td>
                        <p>{{ download.filename }}</p>
                        <small>From <a href="{{ download.referer }}">{{ download.referer }}</a></small>
                    </td>
                    <td class="action">
                        <a href="{{ path('app_download', {id: download.id}) }}" class="fa fa-play"></a>
                        <a href="{{ path('app_delete', {id: download.id}) }}" class="fa fa-remove" onclick="return window.confirm('Remove {{ download.filename }}?')"></a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </main>
    <footer>
        {% if firstPage %}
            <span class="fa fa-chevron-left disabled"></span>
        {% else %}
            {% if showDownloaded %}
                <a href="{{ path('app_list_all_downloads', {page: page-1}) }}" class="fa fa-chevron-left"></a>
            {% else %}
                <a href="{{ path('app_list_downloads', {page: page-1}) }}" class="fa fa-chevron-left"></a>
            {% endif %}
        {% endif %}
        {{ page }} of {{ pageCount }}
        {% if lastPage %}
            <span class="fa fa-chevron-right disabled"></span>
        {% else %}
            {% if showDownloaded %}
                <a href="{{ path('app_list_all_downloads', {page: page+1}) }}" class="fa fa-chevron-right"></a>
            {% else %}
                <a href="{{ path('app_list_downloads', {page: page+1}) }}" class="fa fa-chevron-right"></a>
            {% endif %}
        {% endif %}
    </footer>
{% endblock %}

src/AppBundle/Resources/views/Default/notification.html.twig
{% extends '::base.html.twig' %}

{% block title %}
    #{{ notification.id }} - {{ notification.title }} -
{% endblock %}

{% block header %}
    <header>
        <a href="{{ path('app_list_downloads', {page: 1}) }}"><span class="fa fa-arrow-left"></span> Overview</a>
        <div class="stats">
            <span>Downloads: {{ stats['Not Downloaded'] }} / {{ stats['Total'] }}</span>
            <span>Enqueued: {{ stats['Enqueued'] }}</span>
        </div>
    </header>
{% endblock %}

{% block body %}
    <main class="notification {{ notification.type }}">
        <p>{{ notification.text }}</p>
        {% if '//' in notification.url %}<code>URL: <a href="{{ notification.url }}">{{ notification.url }}</a></code><br/>{% endif %}
        {% if '//' in notification.referer %}<code>Referer: <a href="{{ notification.referer }}">{{ notification.referer }}</a></code>{% endif %}
    </main>
{% endblock %}